import {defineField, defineType} from 'sanity'

export const substackPublicationStrategy = defineType({
  name: 'substackPublicationStrategy',
  title: 'Substack発行戦略（Substack Publication Strategy）',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'タイトル（Title）',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'スラッグ（Slug）',
      type: 'slug',
      options: {source: 'title'},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'sourceContentIdea',
      title: '主軸の知識アイデア（Primary Content Idea）',
      type: 'reference',
      to: [{type: 'contentIdea'}],
      description: 'このSubstack publicationの中心テーマとなるContent Idea。',
    }),
    defineField({
      name: 'relatedContentIdeas',
      title: '関連する知識アイデア（Related Content Ideas）',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'contentIdea'}]}],
      description: 'publicationを支える他のContent Idea群。',
    }),
    defineField({
      name: 'targetReader',
      title: '想定読者（Target Reader）',
      type: 'text',
      rows: 3,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'positioningStatement',
      title: 'ポジショニング（Positioning Statement）',
      type: 'text',
      rows: 3,
      description: '誰のために、何を扱い、どんな違いがあるpublicationかを1段落で。',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'coreTopics',
      title: 'コアトピック（Core Topics, 1〜3個）',
      type: 'array',
      of: [{type: 'string'}],
      validation: (Rule) => Rule.required().min(1).max(3),
    }),
    defineField({
      name: 'publicationPromise',
      title: '読者への約束（Publication Promise）',
      type: 'text',
      rows: 3,
      description: '購読すると何が届くか、どんな変化が期待できるか。',
    }),
    defineField({
      name: 'freeContentRole',
      title: '無料コンテンツの役割（Free Content Role）',
      type: 'text',
      rows: 3,
      description: 'best public workとしてどう位置付けるか。',
    }),
    defineField({
      name: 'paidContentRole',
      title: '有料コンテンツの役割（Paid Content Role）',
      type: 'text',
      rows: 3,
      description: 'backstage-pass / template / cohortなど、laterで扱う形。急がない前提。',
    }),
    defineField({
      name: 'notesRole',
      title: 'Notesの役割（Notes Role）',
      type: 'text',
      rows: 3,
      description: 'discovery、conversation、Post連動などの目的。',
    }),
    defineField({
      name: 'postRole',
      title: 'Postsの役割（Posts Role）',
      type: 'text',
      rows: 3,
      description: 'trust、email delivery、archive、subscriber asset。',
    }),
    defineField({
      name: 'subscriberCTA',
      title: '購読CTA案（Subscriber CTA）',
      type: 'text',
      rows: 3,
      description: 'soft CTAの定型文。煽らない。',
    }),
    defineField({
      name: 'aboutPageDraft',
      title: 'About Page下書き（About Page Draft）',
      type: 'text',
      rows: 6,
    }),
    defineField({
      name: 'welcomeEmailDraft',
      title: 'Welcome Email下書き（Welcome Email Draft）',
      type: 'text',
      rows: 6,
    }),
    defineField({
      name: 'voiceContentFormat',
      title: '差別化軸（Voice / Content / Format）',
      type: 'object',
      fields: [
        defineField({name: 'voice', title: 'Voice', type: 'text', rows: 2}),
        defineField({name: 'content', title: 'Content', type: 'text', rows: 2}),
        defineField({name: 'format', title: 'Format', type: 'text', rows: 2}),
      ],
    }),
    defineField({
      name: 'status',
      title: '状態（Status）',
      type: 'string',
      initialValue: 'draft',
      options: {
        list: [
          {title: '下書き（draft）', value: 'draft'},
          {title: '戦略確定（strategy-ready）', value: 'strategy-ready'},
          {title: '運用中（in-use）', value: 'in-use'},
          {title: '要レビュー（needs-review）', value: 'needs-review'},
          {title: 'アーカイブ済み（archived）', value: 'archived'},
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'reviewNotes',
      title: 'レビューメモ（Review Notes）',
      type: 'text',
      rows: 3,
    }),
  ],
  preview: {
    select: {title: 'title', subtitle: 'status'},
  },
})
